export const MONACO_EDITOR_THEMES = {
  VS: 'vs',
  VSDARK: 'vs-dark',
  HCLIGHT: 'hc-light',
  HCBLACK: 'hc-black',
} as const

export const MONACO_EDITOR_THEME_LIST = [
  MONACO_EDITOR_THEMES.VS,
  MONACO_EDITOR_THEMES.VSDARK,
  MONACO_EDITOR_THEMES.HCLIGHT,
  MONACO_EDITOR_THEMES.HCBLACK,
] as const

export const MONACO_EDITOR_LANGUAGES = {
  CSS: 'css',
  HTML: 'html',
  JSON: 'json',
  TYPESCRIPT: 'typescript',
  JAVASCRIPT: 'javascript',
} as const

export const MONACO_EDITOR_LANGUAGE_LIST = [
  MONACO_EDITOR_LANGUAGES.CSS,
  MONACO_EDITOR_LANGUAGES.HTML,
  MONACO_EDITOR_LANGUAGES.JSON,
  MONACO_EDITOR_LANGUAGES.TYPESCRIPT,
  MONACO_EDITOR_LANGUAGES.JAVASCRIPT,
] as const
